# this is the workflow name
name: hello workflow

on:
  push:
    branches:
      - main

# these are the jobs inside the workflow
jobs:

  # this is name of job
  greet:
    # this is a github runner
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to users
        run: echo "Hello Dosto"

      - name: Say hello to user name
        run: echo "Hello $USER"
