name: Portfolio

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # Upload static files
      - name: Upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./   # change if your index.html is inside a folder like ./dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
